[package]
name = "zeroconf-tokio"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
tokio = { version = "1.39.1", features = ["rt", "sync", "macros", "rt-multi-thread"] }
tokio-util = "0.7.11"
zeroconf = { path = "../../zeroconf-rs/zeroconf" }
